// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PracticaDatos
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Nombre")]
            public string Nombre { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Pocisi�n")]
            public string Pocisi_n { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Juegos")]
            public float Juegos { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Hits")]
            public float Hits { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Carreras")]
            public float Carreras { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"HomeRuns")]
            public float HomeRuns { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"PromedioBateo")]
            public float PromedioBateo { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Nombre")]
            public float[] Nombre { get; set; }

            [ColumnName(@"Pocisi�n")]
            public float[] Pocisi_n { get; set; }

            [ColumnName(@"Juegos")]
            public float Juegos { get; set; }

            [ColumnName(@"Hits")]
            public float Hits { get; set; }

            [ColumnName(@"Carreras")]
            public float Carreras { get; set; }

            [ColumnName(@"HomeRuns")]
            public float HomeRuns { get; set; }

            [ColumnName(@"PromedioBateo")]
            public float PromedioBateo { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
